version: "3"
services:
    web:
        image: molin0000/dex-web:0.1.1
        container_name: hydro-scaffold-dex-web
        ports:
          - 127.0.0.1:8000:8043
        environment:
          - CONFIG_VARS=REACT_APP_API_URL,REACT_APP_WS_URL,REACT_APP_NODE_URL,REACT_APP_HYDRO_PROXY_ADDRESS,REACT_APP_HYDRO_TOKEN_ADDRESS,REACT_APP_WWAN_TOKEN_ADDRESS,REACT_APP_NETWORK_ID,REACT_APP_OPERATOR_ID
          - REACT_APP_API_URL=https://demodex.wandevs.org:43001
          - REACT_APP_WS_URL=wss://demodex.wandevs.org:43002
          - REACT_APP_NODE_URL=https://demodex.wandevs.org:48545
          - REACT_APP_HYDRO_PROXY_ADDRESS=0x9e57b9f1d836ff1701e441a619cbaad7fc8863d3
          - REACT_APP_HYDRO_TOKEN_ADDRESS=0x90fb6abca9aa83044abcdaa6f0bf2fb3d63fa45a
          - REACT_APP_WWAN_TOKEN_ADDRESS=0x916283cc60fdaf05069796466af164876e35d21f
          - REACT_APP_NETWORK_ID=3
          - REACT_APP_OPERATOR_ID=1
        restart: always